### ISSUE TITLE
Floyd-Warshall path reconstruction

### ISSUE THREAD

**Issue by mreinstein** [BrunoRB/algorithms.coffee#5]
I'd like to provide a way to get at the shortest paths, as per  https://en.wikipedia.org/wiki/Floyd%E2%80%93Warshall_algorithm#Path_reconstruction

But I noticed that the existing implementation only returns the shortest paths matrix. 

Is this something you'd take a pull request for? If so, what should the API look like?

thanks for a great algorithms collection!

**Comment by BrunoRB** [comment]
Hi mreinstein and sorry for the long time to reply, I've been really busy lately and still didn't found the time to give a good look at your suggestion, but at first it seems great so feel free to send a pull request with what you have in mind and later we can merge it with the current, or even leave the two as alternatives.
